"""dono_id em atividades

Revision ID: 04b4585e1c16
Revises: c3f8fd77e326
Create Date: 2026-09-24 19:55:00.318580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04b4585e1c16'
down_revision: Union[str, Sequence[str], None] = 'c3f8fd77e326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dono_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_atividades_dono', 'usuarios', ['dono_id'], ['id'])
        batch_op.drop_column('aluno_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_atividades_dono', type_='foreignkey')
        batch_op.drop_column('dono_id')

    # ### end Alembic commands ###
